name: Test Build of conda packages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - test

jobs:
  conda_deployment_with_new_tag:
    name: Test conda deployment of package with Python ${{ matrix.python-version }}
    strategy:
      matrix:
        platform: [macos-13, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: conda.recipe/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: true
          show-channel-urls: true
      - name: Install package
        run: |
          git submodule init
          git submodule update
          pip install .
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: conda.recipe
          python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
          platform_linux-64: false
          platform_osx-64: false
          platform_win-64: false
          user: rceccaroni
          label: dev
          upload: true
          token: ${{ secrets.CONDA_API_TOKEN }} # Replace with the right name of your secret
